### ISSUE TITLE
Problem with combine tree supports 

### ISSUE THREAD

**Issue by abdo3a** [pgfoster/p4-phylogenetics#10]
when i tried combine tree supports from two analyses onto one tree.
i got None/None

**Comment by pgfoster** [comment]
Firstly, can you confirm that the Example found in 
`share/Examples/F_picture/E_combiningSplitSupports`
works?

If if works, but your trees do not, then you can ask how your trees differ from those in the Example.
It may be that not all of the splits in your master tree have support values as node names.  Node names follow the unparen in the Newick tree description like this

```
((A, B)myNodeName, C, D);
```
Perhaps your support values are placed in your trees in a non-standard way?

**Comment by abdo3a** [comment]
Thanks pgfoster for your reply,
i got it now, my values were something ' [&label=47]' and once i removed
everything and just keep values it's working

now, i wondering if it possible using p4 to something like:

if i have multiple gene copies for the same taxon and i want to know if
this multiple copies lying in the same clade or not.

do you have any examples to do this?

Best Regards


*Abdoallah Sharaf*, Ph.D.

Postdoc. Fellow In Biology Centre ASCR
Institute of Parasitology
Branišovská 31
37005 České Budějovice, Czech Republic

and

Assistant Professor, Genetic Department
Faculty of Agriculture
Ain Shams University

**Comment by pgfoster** [comment]
> i got it now, my values were something ' [&label=47]' and once i removed everything and just keep values it's working 

OK, then the problem was that the support was in the tree as a Nexus "command comment".  You can get command comments in a Beast tree by setting

```
var.nexus_getAllCommandComments = True
var.nexus_readBeastTreeCommandComments = True
```
and then the various command comments will be placed on the Node objects of the Tree.

> now, i wondering if it possible using p4 to something like: if i have multiple gene copies for the same taxon and i want to know if this multiple copies lying in the same clade or not. do you have any examples to do this? 

Sorry, no examples come to mind.  However the tools for querying trees exist in p4.  Poke around to see what is there.

**Comment by abdo3a** [comment]
*Sorry Peter for disturbance,*

*i have this issue:*

*when i use mytree.taxNames it return with empty list also with
mytree.getAllLeafNames function*
*in the time another function like my mytree.nodes is working*
*even when i used a tree from your examples, i had the same*
*so what is the problem?*


*Abdoallah Sharaf*, Ph.D.

Postdoc. Fellow In Biology Centre ASCR
Institute of Parasitology
Branišovská 31
37005 České Budějovice, Czech Republic

and

Assistant Professor, Genetic Department
Faculty of Agriculture
Ain Shams University

**Comment by pgfoster** [comment]
> when i use mytree.taxNames it return with empty list

The order of the taxNames is often important, and so I have made it so that it must be set explicitly.  An easy source of ordered taxNames is from an alignment, such as

```
a = func.readAndPop('myDataFile.nex')
t = func.readAndPop('mySingleTree.phy')
t.taxNames = a.taxNames
```

**Comment by abdo3a** [comment]
Thanks peter, i got it

Now, a couple of issues has been arising:

- how to get the node number of a taxon in a tree?

- is any examples of using taxSetIsASplit function?

Regards


*Abdoallah Sharaf*, Ph.D.

Postdoc. Fellow In Biology Centre ASCR
Institute of Parasitology
Branišovská 31
37005 České Budějovice, Czech Republic

and

Assistant Professor, Genetic Department
Faculty of Agriculture
Ain Shams University

**Comment by pgfoster** [comment]
> how to get the node number of a taxon in a tree? 

That is fairly well documented in the doc strings in the Tree class.

```
myNodeNum = t.node('Mastodon').nodeNum
```

> is any examples of using taxSetIsASplit function? 

No, I have not made an example for that.  (It is a method, not a function.)

**Comment by abdo3a** [comment]
*Thanks for your reply Peter,*
* regards to the taxSetIsASplit methods*

*- is it a method that i can check splitting of a set of taxa in my tree?*

*- it's not clear for me, how to use class NexusSets as TaxSet object?*

*-finally, how did you create mysets.nex file in the class NexusSets
examples?*

*Regards *



*Abdoallah Sharaf*, Ph.D.

Postdoc. Fellow In Biology Centre ASCR
Institute of Parasitology
Branišovská 31
37005 České Budějovice, Czech Republic

and

Assistant Professor, Genetic Department
Faculty of Agriculture
Ain Shams University

**Comment by pgfoster** [comment]
> regards to the taxSetIsASplit methods
> - is it a method that i can check splitting of a set of taxa in my tree?

Yes, you could do that.  I find using tax sets (a kind of nexus sets block) to be a little awkward, so I myself don't do that much at all.  There are other ways, such as is given in the "combining splt supports" example. I know that other people use my tree traversal methods but using sets.

> - it's not clear for me, how to use class NexusSets as TaxSet object?
> -finally, how did you create mysets.nex file in the class NexusSets examples?

All things Nexus can be found in Maddison, Swofford, Maddison, 1997.
 DOI: https://doi.org/10.1093/sysbio/46.4.590
It is awkward to make NexuSets (http://p4.nhm.ac.uk/modules/nexus_sets.html) objects programmatically --- it is probably easier to just read in nexus-formatted sets definitions as text.

This has become too far off the original topic, so I am closing this issue.
