### ISSUE TITLE
Documentation at http://p4.nhm.ac.uk/ no longer matches documentation in repository (i.e. seems possibly out-of-date)

### ISSUE THREAD

**Issue by krinsman** [pgfoster/p4-phylogenetics#13]
Admittedly I don't know how this might be fixed, since I don't know how the website http://p4.nhm.ac.uk/ is built, but the website seems to still say that P4 requires Python2 (see image) below, whereas both the `setup.py` and the documentation `INSTALL.rst` found in this repository indicate that P4 has been updated to require Python3.

Maybe the Sphinx source for the website just needs to be refreshed? In any case the discrepancy seems unintentional, so I thought it made sense to try to let someone know. Please let me know whether anything should be clarified.

picture is of http://p4.nhm.ac.uk/installation.html as seen on December 28, 2020

![Снимок экрана 2020-12-28 в 23 14 41](https://user-images.githubusercontent.com/31422259/103258430-c4e95b80-4949-11eb-9453-234170d45125.png)

**Comment by pgfoster** [comment]
@krinsman Thanks for the nudge.  Yes, it was simply out of date.  I refreshed that web page at http://p4.nhm.ac.uk . Now it is at least up-to-date with the source docs (eg now it says it needs Python3).  However, that does not mean that the source docs are up to date with the code ...

**Comment by krinsman** [comment]
No worries, based on the papers I've read so far using it, this seems like a great tool, so just didn't want anyone getting overly incorrect impressions about it based on the documentation. Happy new year!
