### ISSUE TITLE
Request for understanding the nonstationary base composition simulation method in P4.

### ISSUE THREAD

**Issue by BiodeB** [pgfoster/p4-phylogenetics#15]
Dear experts,

I'm a PhD scholar working on evolutionary biology, first time using this software P4 as I have noted some of renowned articles have done the simulations for base compositional heterogeneity across a given tree using P4. However, I'm unable to understand how to achieve it. 

Therefore this is my humble request that it will be an immense help if you some kindly provide some python scripts used in P4 for the simulation of base composition heterogeneity among lineages.

Thanking you,
Debajyoti

**Comment by pgfoster** [comment]
Hi Debajyoti.  There are examples in the share/Examples folder that might help.  For example, see share/Examples/H_calcLike/D_heteroOnTree/sSim.py or share/Examples/H_calcLike/H_remarkable/sSim.py.  Good luck with it.
