### ISSUE TITLE
TypeError: bad operand type for unary -: '_Helper'

### ISSUE THREAD

**Issue by korabeko** [pgfoster/p4-phylogenetics#19]
Dear Peter,
I followed the installation intructions but cannot get p4 running. If it type
p4 --help
I receive the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: bad operand type for unary -: '_Helper'

I have Python3.12.4 on Fedora 40
Any suggestions, please?

**Comment by pgfoster** [comment]
Hi @korabeko, It looks like you were executing the "p4 --help" command from interactive python, probably after importing p4.  You can generate the same sort of error message by starting up interactive python, importing (for example) random, and then doing "random --help" at the python prompt.  

The "p4" command should be called from your (bash or zsh etc) interactive shell, not from interactive python.  P4 is a python package, but it is also a script that you can run at the command line.  You do not need to use the p4 script.  Using the p4 package without the p4 script is more "pythonic", but I find the p4 script to be convenient.  When you import the package in the usual way, you would say "import p4", and that works, and is pythonic.  When you use the p4 script the script does "from p4 import *" which is less pythonic, but I find it convenient.

**Comment by korabeko** [comment]
Thanks a lot, now I see what I did wrong.

st 24. 7. 2024 v 12:13 odesílatel pgfoster ***@***.***>
napsal:
